<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>IDE1006;NU1902;NU1903</WarningsNotAsErrors>
  </PropertyGroup>
  <PropertyGroup>
    <Product>Umbraco.Community.uWis</Product>
    <PackageId>Umbraco.Community.uWis</PackageId>
    <Title>uWis</Title>
    <Description>Automatically sync local video assets from Umbraco to Wistia.</Description>
    <PackageTags>umbraco;umbraco-marketplace</PackageTags>
    <PackageIcon>uwis.png</PackageIcon>
    <Authors>Søren Kottal</Authors>
    <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Søren Kottal</Copyright>
    <PackageProjectUrl>https://github.com/skttl/umbraco-uwis</PackageProjectUrl>
    <RepositoryUrl>https://github.com/skttl/umbraco-uwis</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="18.0.0" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="18.0.0" />
    <PackageReference Include="Umbraco.Cms.Api.Common" Version="18.0.0" />
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="18.0.0" />
  </ItemGroup>
  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />
    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\.github\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\.github\uwis.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
